version: '3.8'

services:
  # Node.js сервис для разработки
  node:
    image: node:${NODE_VERSION}-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${NODE_PORT}:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - snake_network

  # Nginx сервис для проксирования в продакшене
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - node
    networks:
      - snake_network

networks:
  snake_network:
    name: ${COMPOSE_PROJECT_NAME}_network 