name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
      
      - name: Create Vite config if not exists
        run: |
          if [ ! -f "vite.config.js" ]; then
            echo "Creating vite.config.js with base '/snake-3d/'"
            echo "import { defineConfig } from 'vite';
            
            export default defineConfig({
              base: '/snake-3d/',
              build: {
                outDir: 'dist'
              }
            });" > vite.config.js
          else
            echo "vite.config.js already exists, making sure it has the correct base path"
            sed -i -e 's|base: ".*"|base: "/snake-3d/"|g' vite.config.js
            grep -q "base:" vite.config.js || sed -i '/defineConfig/a\  base: "/snake-3d/",' vite.config.js
          fi
          cat vite.config.js
        
      - name: Build
        run: npm run build
      
      - name: Check build output
        run: |
          echo "=== Build output ==="
          ls -la dist
          if [ ! -f "dist/index.html" ]; then
            echo "ERROR: dist/index.html not found!"
            exit 1
          fi
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages